### ISSUE TITLE
Add getBoard function as default export

### ISSUE THREAD

**Issue by egfanboy** [EricTurf/sudoku-generator#1]
add a function called `getBoard` that takes in the difficulty and calls the appropriate function (easy,medium,hard)

Please write unit tests with `jest`

**Comment by matheuscr30** [comment]
Can i do that?

**Comment by iainjreid** [comment]
Hi, I can lend a _hacktoberhand_ on this! Are you after a conversion to `.mjs` (supporting full blown ES6 imports) or are you preferring to move the `module.exports` to expose the `getBoard` function?

**Comment by egfanboy** [comment]
I think an easy fix is to change the current `module.exports` to only be a function that accepts a `difficulty` instead of the current object that has `easy`,`medium`,`hard` keys.

**Comment by iainjreid** [comment]
Hopefully this was what you were after? I've updated the tests accordingly.
